services:
  - type: web
    name: alicia-kevin-wedding-rsvp
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_KEY
        sync: false
